### ISSUE TITLE
General Tracking Issue

### ISSUE THREAD

**Issue by rossbar** [rossbar/sphinx-jupyter-book-theme#1]
# General Issues

Rather than create a new issue for every little thing that pops up, this issue will serve as a running catalog for noting down issues as they arise, with no attempt to scope them out nor prioritize their resolution.

 - [x] Sphinx build: Lots of warnings: `WARNING: Pygments lexer name 'ipython3' is not known`
   * 8b84c2a - Add ipython to dep list
 - [x] sphinx build: `WARNING: nbsphinx_widgets_path not given and ipywidgets module unavailable`
   * e6cc120 - dep list += `ipywidgets`
 - [ ] Sphinx build: myriad warnings related to doc formatting, particularly with `.ipynb` files.
 - Comment: Build time on my system
   ```
   real    0m12.274s
   user    0m8.330s
   sys     0m3.153s
   ```
 - [ ] Replicate toc structure behavior
   * Right now, a flat toc is specified using `:glob:`. This derives it's "nesting" behavior from the header levels in the document. This is different than Jupyterbook, which derives toc levels from user definitions in `toc.yaml`.
   * After more investigation, this is one of the big conceptual sticking points for me. Jupyter-book treats the `toc` as document-level metadata that allows the author to control the layout of the book regardless of file structure. OTOH the sphinx way with `toc` directives results in metadata that define structure being embedded in the documents themselves. It may be possible to replicate Jupyterbook-style behavior with `toc` directives, but it is not immediately obvious to me how this would be accomplished. Perhaps a more experience sphinx user would have insight here.
 - [x] `toctree` directive fails to recognize `.md` files ~when manually specified. The `.md` files are 
   being included with `:glob:`~ Edit: Nope, it was always missing `.md` files I just didn't notice
   with glob
   * ae87c49 - This is "fixed" by including the `recommonmark` extension in `conf.py`.
 - [ ] `recommonmark` extension doesn't respect yaml headers
   * Modify behavior with `AutoStructify`?
   * See https://github.com/readthedocs/commonmark.py/issues/208
